using System;

namespace SAEA.Audio.NAudio.MediaFoundation
{
	public enum MediaEventType
	{
		MEUnknown,
		MEError,
		MEExtendedType,
		MENonFatalError,
		MESessionUnknown = 100,
		MESessionTopologySet,
		MESessionTopologiesCleared,
		MESessionStarted,
		MESessionPaused,
		MESessionStopped,
		MESessionClosed,
		MESessionEnded,
		MESessionRateChanged,
		MESessionScrubSampleComplete,
		MESessionCapabilitiesChanged,
		MESessionTopologyStatus,
		MESessionNotifyPresentationTime,
		MENewPresentation,
		MELicenseAcquisitionStart,
		MELicenseAcquisitionCompleted,
		MEIndividualizationStart,
		MEIndividualizationCompleted,
		MEEnablerProgress,
		MEEnablerCompleted,
		MEPolicyError,
		MEPolicyReport,
		MEBufferingStarted,
		MEBufferingStopped,
		MEConnectStart,
		MEConnectEnd,
		MEReconnectStart,
		MEReconnectEnd,
		MERendererEvent,
		MESessionStreamSinkFormatChanged,
		MESourceUnknown = 200,
		MESourceStarted,
		MEStreamStarted,
		MESourceSeeked,
		MEStreamSeeked,
		MENewStream,
		MEUpdatedStream,
		MESourceStopped,
		MEStreamStopped,
		MESourcePaused,
		MEStreamPaused,
		MEEndOfPresentation,
		MEEndOfStream,
		MEMediaSample,
		MEStreamTick,
		MEStreamThinMode,
		MEStreamFormatChanged,
		MESourceRateChanged,
		MEEndOfPresentationSegment,
		MESourceCharacteristicsChanged,
		MESourceRateChangeRequested,
		MESourceMetadataChanged,
		MESequencerSourceTopologyUpdated,
		MESinkUnknown = 300,
		MEStreamSinkStarted,
		MEStreamSinkStopped,
		MEStreamSinkPaused,
		MEStreamSinkRateChanged,
		MEStreamSinkRequestSample,
		MEStreamSinkMarker,
		MEStreamSinkPrerolled,
		MEStreamSinkScrubSampleComplete,
		MEStreamSinkFormatChanged,
		MEStreamSinkDeviceChanged,
		MEQualityNotify,
		MESinkInvalidated,
		MEAudioSessionNameChanged,
		MEAudioSessionVolumeChanged,
		MEAudioSessionDeviceRemoved,
		MEAudioSessionServerShutdown,
		MEAudioSessionGroupingParamChanged,
		MEAudioSessionIconChanged,
		MEAudioSessionFormatChanged,
		MEAudioSessionDisconnected,
		MEAudioSessionExclusiveModeOverride,
		METrustUnknown = 400,
		MEPolicyChanged,
		MEContentProtectionMessage,
		MEPolicySet,
		MEWMDRMLicenseBackupCompleted = 500,
		MEWMDRMLicenseBackupProgress,
		MEWMDRMLicenseRestoreCompleted,
		MEWMDRMLicenseRestoreProgress,
		MEWMDRMLicenseAcquisitionCompleted = 506,
		MEWMDRMIndividualizationCompleted = 508,
		MEWMDRMIndividualizationProgress = 513,
		MEWMDRMProximityCompleted,
		MEWMDRMLicenseStoreCleaned,
		MEWMDRMRevocationDownloadCompleted,
		METransformUnknown = 600,
		METransformNeedInput,
		METransformHaveOutput,
		METransformDrainComplete,
		METransformMarker
	}
}
